"""ZM-ZEGRID-R3 targeted tests — full-layout executor + deterministic assembly.

Isolated R3 tests over the frozen M106 geometry + prepared RGB fixtures on disk.
They do NOT touch production dispatch. Light tests are geometry/assembly-only
and always run; heavy tests run the REAL R1/R2 pipeline for a bounded set of
Cells and are gated on the strict memory budget (skip, not OOM, when the gate is
unsatisfied).

Artifact note: the full-layout executor + assembly evidence lives OUTSIDE git at
``/home/tristan/zegrid_r3_m106_outputs`` (M106) and
``/home/tristan/zegrid_r3_m16_outputs`` (M16), regenerated by::

    PYTHONPATH=$PWD/src <main .venv>/bin/python tools/zegrid_r3/run_executor.py \
        --lights /home/tristan/M106/lights \
        --fixtures /home/tristan/zegrid_r3_m106_fixtures \
        --out /home/tristan/zegrid_r3_m106_outputs --nx 5 --ny 4
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import numpy as np
import pytest

from zemosaic.core.zegrid import executor as zx
from zemosaic.core.zegrid import geometry as zg
from zemosaic.core.zegrid import mosaic as zm
from zemosaic.core.zegrid import science_adapter as zs
from zemosaic.core.zegrid import sweep as zsw

LIGHTS = Path("/home/tristan/M106/lights")
# Reuse the R2-prepared RGB fixtures (byte-identical decoder + inputs; all 66
# frames already on disk with a recorded manifest sha256).
FIXTURES = Path("/home/tristan/zegrid_r2_fixtures")
R1_PREP = (
    Path("/home/tristan/.openclaw/workspace/worktrees/zemosaic-zegrid-r1")
    / "tools"
    / "zegrid_r1"
    / "prepare_rgb_fixture.py"
)


def _prepared(key: str) -> str:
    return str(FIXTURES / (Path(key).stem + "_rgb.fits"))


def _ensure_fixtures(keys: list[str]) -> None:
    missing = [k for k in keys if not Path(_prepared(k)).exists()]
    if not missing:
        return
    names = ",".join(Path(k).name for k in missing)
    subprocess.run(
        [
            sys.executable,
            str(R1_PREP),
            "--input",
            str(LIGHTS),
            "--output",
            str(FIXTURES),
            "--frames",
            names,
        ],
        check=True,
    )


def _gate_or_skip(n: int):
    gate = zsw.check_memory_gate(n)
    if not gate.ok:
        pytest.skip(
            f"memory gate unsatisfied: available={gate.available/2**30:.2f}GiB "
            f"< required={gate.required/2**30:.2f}GiB"
        )
    return gate


@pytest.fixture(scope="module")
def manifest():
    frames, _ = zg.read_manifest(LIGHTS)
    return frames


@pytest.fixture(scope="module")
def canvas(manifest):
    return zg.build_canvas(manifest)


# ---------------------------------------------------------------------------
# Light tests: row-major order determinism, config, memory gate, assembly
# ---------------------------------------------------------------------------

def test_cell_order_is_row_major_deterministic(manifest, canvas):
    order = zx.cell_order(canvas, 5, 4)
    # 20 cells, exact row-major sequence.
    assert len(order) == 20
    expected = [
        (r, c, zg.cell_id(r, c)) for r in range(4) for c in range(5)
    ]
    assert order == expected
    # Row-major == Cell-ID sorted (r%04dc%04d).
    assert [cid for _r, _c, cid in order] == sorted(zg.cell_id(r, c) for r in range(4) for c in range(5))


def test_executor_config_pins_sky_mean_labelled(manifest, canvas):
    cfg = zx.ExecutorConfig()
    assert cfg.normalization == "sky_mean"
    assert cfg.r1_frozen_default == "linear_fit"
    assert cfg.weighting == "noise_variance"
    assert cfg.rejection == "kappa_sigma"
    assert cfg.combine == "mean"
    assert cfg.backend == "cpu"
    assert cfg.taper == "footprint"
    assert cfg.taper_px == 8.0
    assert cfg.taper_floor == 0.0
    assert cfg.variant_reason


def test_cell_order_permutation_invariant(manifest, canvas):
    base = zx.cell_order(canvas, 5, 4)
    rev = zx.cell_order(zg.build_canvas(list(reversed(manifest))), 5, 4)
    assert base == rev


def test_memory_gate_present(monkeypatch):
    monkeypatch.setattr(zsw, "read_available_memory", lambda: int(0.5 * 1024**3))
    assert zsw.check_memory_gate(23).ok is False
    monkeypatch.setattr(zsw, "read_available_memory", lambda: int(3.0 * 1024**3))
    assert zsw.check_memory_gate(66).ok is True


def test_assembly_exact_one_owner_synthetic(canvas):
    """Assembly places each core exactly once; disjoint + exhaustive, no gaps."""
    nx, ny = 5, 4
    layout = zg.build_layout(canvas, nx, ny)
    cores: dict[str, dict] = {}
    for row, col, cid in zx.cell_order(canvas, nx, ny):
        b = layout.cell_bounds(row, col, canvas)
        h, w = b.height, b.width
        cores[cid] = {
            "science_core": np.full((h, w, 3), 1.0, dtype=np.float32),
            "surviving_sample_count_core": np.full((h, w, 3), 3, dtype=np.int32),
            "n_eff_support_core": np.full((h, w), 3.0, dtype=np.float64),
            "support_w1_core": np.full((h, w), 1.0, dtype=np.float64),
            "support_w2_core": np.full((h, w), 1.0, dtype=np.float64),
            "valid_mask_core": np.full((h, w, 3), True, dtype=bool),
        }
    a = zm.assemble_canvas(canvas, nx, ny, cores)
    seen = zm.verify_disjoint_exhaustive(a)
    assert int(seen.min()) == 1 and int(seen.max()) == 1
    assert a.hole_pixels == 0
    assert a.incomplete_cells == []
    # Coverage/support planes preserved (never inferred from brightness).
    assert a.stack_depth.shape == (canvas.height, canvas.width)
    assert int(a.stack_depth.min()) == 3 and int(a.stack_depth.max()) == 3
    assert np.isfinite(a.n_eff_support).all()
    assert a.science.shape == (canvas.height, canvas.width, 3)


def test_assembly_holes_explicit(manifest, canvas):
    """A missing Cell leaves an explicit coverage==0 hole (never silently filled)."""
    nx, ny = 5, 4
    layout = zg.build_layout(canvas, nx, ny)
    cores: dict[str, dict | None] = {}
    for row, col, cid in zx.cell_order(canvas, nx, ny):
        if cid == "r0000c0000":
            cores[cid] = None  # incomplete cell
            continue
        b = layout.cell_bounds(row, col, canvas)
        h, w = b.height, b.width
        cores[cid] = {
            "science_core": np.full((h, w, 3), 1.0, dtype=np.float32),
            "surviving_sample_count_core": np.full((h, w, 3), 3, dtype=np.int32),
            "n_eff_support_core": np.full((h, w), 3.0, dtype=np.float64),
            "support_w1_core": np.full((h, w), 1.0, dtype=np.float64),
            "support_w2_core": np.full((h, w), 1.0, dtype=np.float64),
            "valid_mask_core": np.full((h, w, 3), True, dtype=bool),
        }
    a = zm.assemble_canvas(canvas, nx, ny, cores)
    # The missing cell's core is a hole.
    b = layout.cell_bounds(0, 0, canvas)
    assert a.hole_pixels == b.width * b.height
    assert a.incomplete_cells == ["r0000c0000"]
    # Science is NaN inside the hole, finite elsewhere.
    hole = a.science[b.y0:b.y1, b.x0:b.x1]
    assert np.isnan(hole).all()
    # ownership: 19 cells each owned once; the missing cell owned 0 times.
    assert int(a.owner[b.y0:b.y1, b.x0:b.x1].max()) == 0
    assert int(a.owner.max()) == 1


def test_assembly_shape_mismatch_raises(manifest, canvas):
    """A core whose shape does not match its layout bounds raises."""
    nx, ny = 2, 1
    layout = zg.build_layout(canvas, nx, ny)
    b = layout.cell_bounds(0, 0, canvas)
    bad = {
        # Wrong height -> placement would silently corrupt the canvas; must raise.
        "science_core": np.full((b.height - 1, b.width, 3), 1.0, dtype=np.float32),
        "surviving_sample_count_core": np.full((b.height, b.width, 3), 1, dtype=np.int32),
        "n_eff_support_core": np.full((b.height, b.width), 1.0, dtype=np.float64),
        "support_w1_core": np.full((b.height, b.width), 1.0, dtype=np.float64),
        "support_w2_core": np.full((b.height, b.width), 1.0, dtype=np.float64),
        "valid_mask_core": np.full((b.height, b.width, 3), True, dtype=bool),
    }
    with pytest.raises(AssertionError):
        zm.assemble_canvas(canvas, nx, ny, {"r0000c0000": bad})


# ---------------------------------------------------------------------------
# Heavy tests: real full-layout executor + assembly (gated on fixtures + memory)
# ---------------------------------------------------------------------------

def _run_cell(manifest, canvas, row, col):
    _cell, _patch, mem = zsw.build_cell_context(manifest, canvas, row, col, 5, 4)
    keys = list(mem.patch_ids)
    _gate_or_skip(len(keys))
    _ensure_fixtures(keys)
    prepared = {k: _prepared(k) for k in keys}
    return zx.run_cell_executor(
        manifest, canvas, prepared, row, col, zx.ExecutorConfig(),
        nx=5, ny=4,
    )


@pytest.fixture(scope="module")
def corner_exec(manifest, canvas):
    return _run_cell(manifest, canvas, 0, 0)


def test_executor_corner_cell_complete(corner_exec):
    res = corner_exec
    assert res.cell_id == "r0000c0000"
    assert res.status == zx.STATUS_COMPLETE
    assert res.n_patch_contributors == 7
    assert res.n_core_contributors == 5
    assert res.adequacy is not None
    # sky_mean variant: the corner is still a shallow/possibly single-frame cell,
    # but the record must be explicit and non-silent.
    assert res.adequacy["total_contributors"] == 7
    assert res.peak_rss_kib > 0
    assert res.section_read_count == 7


def test_executor_rerun_stable(manifest, canvas, corner_exec):
    """Per-cell result is stable on rerun (deterministic executor)."""
    rev = _run_cell(manifest, canvas, 0, 0)
    assert rev.adequacy == corner_exec.adequacy
    assert rev.reference_frame_id == corner_exec.reference_frame_id
    assert rev.excluded == corner_exec.excluded
    assert rev.n_patch_contributors == corner_exec.n_patch_contributors


# ---------------------------------------------------------------------------
# R3 full-layout + assembly artifact guards (read persisted outputs; skip if absent)
# ---------------------------------------------------------------------------

def _load_persisted_layout(out_dir: str):
    out = Path(out_dir)
    manifest_path = out / "assembly_manifest.json"
    if not manifest_path.exists():
        pytest.skip(f"no R3 assembly manifest at {out_dir}")
    return json.loads(manifest_path.read_text())


def test_m106_full_layout_manifest_present():
    manifest = _load_persisted_layout("/home/tristan/zegrid_r3_m106_outputs")
    assert manifest["canvas"]["width"] == 2403
    assert manifest["canvas"]["height"] == 3278
    assert manifest["layout"] == {"nx": 5, "ny": 4, "halo_px": 8}
    # All 20 cells accounted.
    assert len(manifest["cells"]) == 20
    statuses = [c.get("status") for c in manifest["cells"].values()]
    # Empty/incomplete/killed cells are explicit (never silently skipped).
    for st in statuses:
        assert st in (
            zx.STATUS_COMPLETE, zx.STATUS_EMPTY, zx.STATUS_INCOMPLETE,
            zx.STATUS_BLOCKED_MEMORY, zx.STATUS_KILLED,
        )
    # Ownership: one-owner per pixel (disjoint + exhaustive), holes explicit.
    assert "ownership" in manifest
    assert "holes" in manifest


def test_m106_assembly_coverage_preserved():
    manifest = _load_persisted_layout("/home/tristan/zegrid_r3_m106_outputs")
    assert manifest["holes"]["coverage_pixels"] > 0
    # If any cell is incomplete, holes must be > 0 and the cell listed.
    if manifest["holes"]["incomplete_cells"]:
        assert manifest["holes"]["hole_pixels"] > 0


# ---------------------------------------------------------------------------
# M16 depth guard (Scope C): >=1 cell with effective contributors >= 20
# ---------------------------------------------------------------------------

def test_m16_depth_guard():
    out = Path("/home/tristan/zegrid_r3_m16_outputs")
    manifest_path = out / "assembly_manifest.json"
    if not manifest_path.exists():
        pytest.skip("no M16 R3 assembly manifest (run tools/zegrid_r3/run_executor.py)")
    manifest = json.loads(manifest_path.read_text())
    effs = [
        (cid, c.get("adequacy", {}).get("effective_contributor_count", 0))
        for cid, c in manifest["cells"].items()
        if c.get("status") == zx.STATUS_COMPLETE
    ]
    if not effs:
        pytest.skip("no complete M16 cells to assert depth")
    best = max(effs, key=lambda t: t[1])
    assert best[1] >= 20, (
        f"M16 depth guard BLOCKED: max effective contributors = {best[1]} "
        f"(cell {best[0]}), expected >= 20"
    )
