"""ZM-ZEGRID-R2 targeted tests — multi-frame witness sweep + adjacent-Cell continuity.

These are isolated R2 tests over the frozen M106 geometry + prepared RGB
fixtures on disk (``/home/tristan/zegrid_r2_fixtures``; NEVER ``/tmp``). They do
not touch production dispatch. Heavy tests run the REAL R1 local pipeline for a
bounded set of Cells and are gated on the strict memory budget (skip, not OOM,
when the gate is unsatisfied); light tests are geometry-only and always run.

Note (artifacts, L1): the seam/adequacy evidence artifacts live OUTSIDE git at
``/home/tristan/zegrid_r2_outputs`` (prepared fixtures at
``/home/tristan/zegrid_r2_fixtures``) and are regenerated by::

    PYTHONPATH=$PWD/src <main .venv>/bin/python tools/zegrid_r2/sweep_multiframe.py

so a clean checkout's skip of the tests that read those artifacts (chosen-cell
guard + seam diagnostic) is unambiguous.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import numpy as np
import pytest

from zemosaic.core.zegrid import execution as zx
from zemosaic.core.zegrid import geometry as zg
from zemosaic.core.zegrid import science_adapter as zs
from zemosaic.core.zegrid import seam as zsm
from zemosaic.core.zegrid import sweep as zsw

LIGHTS = Path("/home/tristan/M106/lights")
FIXTURES = Path("/home/tristan/zegrid_r2_fixtures")
R1_PREP = (
    Path("/home/tristan/.openclaw/workspace/worktrees/zemosaic-zegrid-r1")
    / "tools"
    / "zegrid_r1"
    / "prepare_rgb_fixture.py"
)


def _prepared(key: str) -> str:
    return str(FIXTURES / (Path(key).stem + "_rgb.fits"))


def _ensure_fixtures(keys: list[str]) -> None:
    missing = [k for k in keys if not Path(_prepared(k)).exists()]
    if not missing:
        return
    names = ",".join(Path(k).name for k in missing)
    subprocess.run(
        [
            sys.executable,
            str(R1_PREP),
            "--input",
            str(LIGHTS),
            "--output",
            str(FIXTURES),
            "--frames",
            names,
        ],
        check=True,
    )


def _gate_or_skip(n: int):
    gate = zsw.check_memory_gate(n)
    if not gate.ok:
        pytest.skip(
            f"memory gate unsatisfied: available={gate.available/2**30:.2f}GiB "
            f"< required={gate.required/2**30:.2f}GiB"
        )
    return gate


@pytest.fixture(scope="module")
def manifest(m106_corpus):
    frames, _rejected, _canvas = m106_corpus
    return frames


@pytest.fixture(scope="module")
def canvas(m106_corpus):
    _frames, _rejected, canvas = m106_corpus
    return canvas


# ---------------------------------------------------------------------------
# Light tests: sweep determinism, ordering, ownership, memory gate (no fixtures)
# ---------------------------------------------------------------------------

def test_candidate_order_matches_expected(manifest, canvas):
    cands = zsw.candidate_order(manifest, canvas)
    order = [c.cell_id for c in cands]
    # frozen corner r0000c0000 and symmetric weak corner r0003c0004 are excluded.
    assert "r0000c0000" not in order
    assert "r0003c0004" not in order
    # deterministic ascending N, tie-break by cell id.
    for i in range(len(cands) - 1):
        assert (cands[i].n_contributors, cands[i].cell_id) <= (
            cands[i + 1].n_contributors,
            cands[i + 1].cell_id,
        )
    # first candidate is the lowest-N non-corner cell.
    assert order[0] == "r0000c0001"


def test_witness_sweep_determinism(manifest, canvas):
    base = zsw.candidate_order(manifest, canvas)
    rev = zsw.candidate_order(list(reversed(manifest)), canvas)
    again = zsw.candidate_order(manifest, canvas)
    assert [(c.cell_id, c.n_contributors) for c in base] == [
        (c.cell_id, c.n_contributors) for c in rev
    ]
    assert [c.cell_id for c in base] == [c.cell_id for c in again]


def test_memory_gate_present(monkeypatch):
    # skip/abort path tested without OOM.
    monkeypatch.setattr(zsw, "read_available_memory", lambda: int(0.5 * 1024**3))
    gate = zsw.check_memory_gate(23)
    assert gate.ok is False
    assert gate.required == zsw.MIN_AVAILABLE_BYTES
    # extended threshold for N > 28.
    monkeypatch.setattr(zsw, "read_available_memory", lambda: int(1.5 * 1024**3))
    gate2 = zsw.check_memory_gate(36)
    assert gate2.required == zsw.EXTENDED_AVAILABLE_BYTES
    assert gate2.ok is False  # 1.5 GiB < 1.6 GiB
    # sufficient memory -> ok.
    monkeypatch.setattr(zsw, "read_available_memory", lambda: int(3.0 * 1024**3))
    assert zsw.check_memory_gate(36).ok is True


def test_core_ownership_exactness(manifest, canvas):
    layout = zg.build_layout(canvas, 5, 4)
    owned = zsm.assert_core_partition_exact(layout, canvas)
    assert int(owned.min()) == 1 and int(owned.max()) == 1


# ---------------------------------------------------------------------------
# Heavy tests: real stacks (gated on fixtures + memory)
# ---------------------------------------------------------------------------

def _run_cell(manifest, canvas, row, col, normalization="linear_fit"):
    _cell, _patch, mem = zsw.build_cell_context(manifest, canvas, row, col)
    keys = list(mem.patch_ids)
    _gate_or_skip(len(keys))
    _ensure_fixtures(keys)
    prepared = {k: _prepared(k) for k in keys}
    return zsw.run_cell_stack(
        manifest,
        canvas,
        prepared,
        row,
        col,
        zs.MiniTileScienceConfig(normalization=normalization),
    )


@pytest.fixture(scope="module")
def corner_run(manifest, canvas):
    # FROZEN linear_fit config (R1 default) — documented config-sensitivity control.
    return _run_cell(manifest, canvas, 0, 0, "linear_fit")


@pytest.mark.slow
def test_corner_cell_single_frame_guard(corner_run):
    res = corner_run
    assert res.cell_id == "r0000c0000"
    assert res.adequacy.total_contributors == 7
    assert res.adequacy.effective_contributor_count == 1
    assert res.adequacy.single_frame_witness is True
    assert res.adequacy.excluded_count == 6


@pytest.mark.slow
def test_section_read_locality(manifest, canvas, corner_run):
    res = corner_run
    assert len(res.section_reads) == 7
    for rec in res.section_reads:
        assert rec.n_pixels_read < rec.full_frame_pixels  # never full .data
        assert rec.source_bounds.width * rec.source_bounds.height * 3 == rec.n_pixels_read


@pytest.mark.slow
def test_permutation_determinism(manifest, canvas, corner_run):
    # Same cell, reversed frame list -> identical reference/exclusion/adequacy.
    rev = _run_cell(manifest, canvas, 0, 0, "linear_fit")  # sorts internally
    base = corner_run
    assert rev.reference_frame_id == base.reference_frame_id
    assert rev.excluded == base.excluded
    assert rev.adequacy.effective_contributor_count == base.adequacy.effective_contributor_count
    assert rev.adequacy.valid_fraction == base.adequacy.valid_fraction


# ---------------------------------------------------------------------------
# Rework: sky_mean variant — normalization-only defect evidence (no full stack)
# ---------------------------------------------------------------------------

@pytest.mark.slow
def test_normalization_defect_evidence(manifest, canvas):
    """Document the linear_fit defect on real contributors (normalization-only).

    On r0002c0000 (near-full coverage, 97.5% valid), the SCI-05 ``linear_fit``
    normalization excludes EVERY non-reference frame (``slope_out_of_range``),
    leaving a single-frame witness; ``sky_mean`` keeps all 23 contributors. This
    runs only the B1 normalization stage (no weighting/rejection/combine).
    """
    from zemosaic.core.canonical_stacking import (
        normalize_canonical_images,
        prepare_canonical_inputs,
    )

    _cell, patch, mem = zsw.build_cell_context(manifest, canvas, 2, 0)  # r0002c0000
    keys = list(mem.patch_ids)
    _gate_or_skip(len(keys))
    _ensure_fixtures(keys)
    prepared = {k: _prepared(k) for k in keys}
    by_id = {f.frame_id.logical_path: f for f in manifest}
    patch_frames = [by_id[k] for k in keys]
    crop_plans = {
        f.frame_id.logical_path: zg.plan_source_roi(f, canvas, patch)
        for f in patch_frames
    }
    contribs = zx.build_patch_contributors(
        patch_frames, prepared, canvas, patch, crop_plans
    )
    batch = prepare_canonical_inputs(
        [c.rgb for c in contribs], [c.geometric_support for c in contribs]
    )
    lin = normalize_canonical_images(batch, "linear_fit")
    sky = normalize_canonical_images(batch, "sky_mean")
    lin_active = int(np.sum(lin.active_frames))
    sky_active = int(np.sum(sky.active_frames))
    # linear_fit excludes every non-reference frame (slope_out_of_range).
    assert lin_active == 1
    assert {e.reason for e in lin.exclusions} == {"slope_out_of_range"}
    # sky_mean keeps all contributors.
    assert sky_active == len(contribs)


# ---------------------------------------------------------------------------
# Rework: sky_mean chosen-cell guard + adjacent-Cell seam (multi-frame)
# ---------------------------------------------------------------------------

@pytest.fixture(scope="module")
def chosen_run(manifest, canvas):
    import json

    summary_path = Path("/home/tristan/zegrid_r2_outputs/sweep_summary.json")
    if summary_path.exists():
        summary = json.loads(summary_path.read_text())
        chosen = summary.get("chosen_cell")
        if chosen is None:
            pytest.skip("BLOCKED: no candidate reached effective>=3 under sky_mean")
        rec = json.loads(
            (Path("/home/tristan/zegrid_r2_outputs") / f"minitile_{chosen}.json").read_text()
        )
        assert rec["normalization_method"] == "sky_mean"
        cand = next(
            c for c in zsw.candidate_order(manifest, canvas) if c.cell_id == chosen
        )
        return cand, rec["adequacy"]
    # Self-contained fallback: bounded sky_mean mini-sweep (same deterministic order).
    for cand in zsw.candidate_order(manifest, canvas)[: zsw.DEFAULT_MAX_CELLS]:
        res = _run_cell(manifest, canvas, cand.row, cand.col, "sky_mean")
        if res.adequacy.effective_contributor_count >= 3:
            return cand, res.adequacy.to_dict()
    pytest.skip("no candidate reached effective>=3 under sky_mean within 6 cells")


@pytest.mark.slow
def test_chosen_cell_multiframe_guard(chosen_run):
    cand, adequacy = chosen_run
    assert adequacy["effective_contributor_count"] >= 3
    assert adequacy["single_frame_witness"] is False


def _load_persisted_minitile_planes(cell_id: str) -> dict:
    import numpy as _np

    p = Path("/home/tristan/zegrid_r2_outputs") / f"minitile_{cell_id}.npz"
    if not p.exists():
        pytest.skip(f"no persisted MiniTile for {cell_id}")
    z = _np.load(p)
    return {
        "science": z["science"],
        "valid_mask": z["valid_mask"],
        "n_eff_support": z["n_eff_support"],
        "surviving_sample_count": z["surviving_sample_count"],
    }


def _rc(cell_id: str) -> tuple[int, int]:
    return int(cell_id[1:5]), int(cell_id[6:10])


@pytest.mark.slow
def test_seam_diagnostic_computed_and_recorded(manifest, canvas):
    """Compute the seam diagnostic on the chosen multi-frame Cell + neighbour."""
    import json

    from types import SimpleNamespace

    summary = json.loads(
        Path("/home/tristan/zegrid_r2_outputs/sweep_summary.json").read_text()
    )
    chosen = summary.get("chosen_cell")
    neighbour = summary.get("neighbour")
    if chosen is None or neighbour is None:
        pytest.skip("no chosen multi-frame cell + neighbour pair persisted")

    ch_cell, ch_patch, _ = zsw.build_cell_context(manifest, canvas, *_rc(chosen))
    nb_cell, nb_patch, _ = zsw.build_cell_context(manifest, canvas, *_rc(neighbour))
    mt_ch = SimpleNamespace(**{
        k: _load_persisted_minitile_planes(chosen)[k]
        for k in ("science", "valid_mask", "n_eff_support", "surviving_sample_count")
    })
    mt_nb = SimpleNamespace(**{
        k: _load_persisted_minitile_planes(neighbour)[k]
        for k in ("science", "valid_mask", "n_eff_support", "surviving_sample_count")
    })

    layout = zg.build_layout(canvas, 5, 4)
    owned = zsm.assert_core_partition_exact(layout, canvas)
    assert int(owned.min()) == 1 and int(owned.max()) == 1

    seam = zsm.compute_seam_diagnostic(
        canvas,
        ch_cell,
        ch_patch,
        mt_ch,
        nb_cell,
        nb_patch,
        mt_nb,
        nx=5,
        ny=4,
        halo_px=zsm.SEAM_HALF,
    )
    assert "residual" in seam
    assert "valid_fraction_abs_diff" in seam["residual"]
    assert "mean_science_abs_diff_per_channel" in seam["residual"]
    assert "measurable_discontinuity" in seam
    assert {seam["low_cell"], seam["high_cell"]} == {chosen, neighbour}
    assert np.isfinite(seam["residual"]["valid_fraction_abs_diff"])
